<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" 
xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://statsq.iac_soap/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://statsq.iac_soap/" name="normaalVerdeling">

	<import namespace="http://api.hu.fnt.nl/normverd" location="normaalVerdelingExtend.wsdl"/>
	<binding xmlns:ns1="http://api.hu.fnt.nl/normverd" name="NormVerdServicePortBinding" type="ns1:NormVerdServiceIF">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
		<operation name="calculateNormVerd">
			<soap:operation soapAction=""/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="normaalVerdeling">
		<port name="NormVerdServicePort" binding="tns:NormVerdServicePortBinding">
			<soap:address location="http://localhost:8080/api/normaalVerdeling"/>
		</port>
	</service>
</definitions>